live_config_reload = true

[window]
dimensions = { columns = 120, lines = 60 }
position = { x = 0, y = 0 }
padding = { x = 0, y = 0 }
startup_mode = "Maximized"
opacity = 1
title = "💀"
dynamic_title = false
decorations_theme_variant = "dark"

[font]
size = 9

[font.bold]
family = "BlexMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "BlexMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "BlexMono Nerd Font"
style = "Italic"

[font.normal]
family = "BlexMono Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = true
bindings = [
  { action = "PasteSelection", mouse = "Middle" },
  { action = "CopySelection", mouse = "Right" },
]

[cursor]
style = { shape = "Beam", blinking = "Always" }
vi_mode_style = "Block"
blink_interval = 300
blink_timeout = 5
unfocused_hollow = true
thickness = 0.15

[keyboard]
bindings = [
  { key = "Escape", mods = "Control", action = "ToggleViMode" },
  { key = "I", mode = "Vi|~Search", action = "ToggleViMode" },
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]


[colors.cursor]
text = "CellBackground"
cursor = "#ff0000"

[colors.vi_mode_cursor]
text = "#2e3440"
cursor = "#d8dee9"

[colors.selection]
text = "CellForeground"
background = "#4c566a"

[colors.search.matches]
foreground = "CellBackground"
background = "#88c0d0"

[colors.footer_bar]
background = "#434c5e"
foreground = "#d8dee9"

## Tomorrow Dark
[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[colors.normal]
black = '#282a2e'
red = '#a54242'
green = '#8c9440'
yellow = '#de935f'
blue = '#5f819d'
magenta = '#85678f'
cyan = '#5e8d87'
white = '#707880'

[colors.bright]
black = '#373b41'
red = '#cc6666'
green = '#b5bd68'
yellow = '#f0c674'
blue = '#81a2be'
magenta = '#b294bb'
cyan = '#8abeb7'
white = '#c5c8c6'
